import { Component, OnDestroy, OnInit } from '@angular/core';
import { ActivatedRoute } from '@angular/router';
import { Subscription } from 'rxjs';
import { ApiService } from '../../../services/api/api.service';

interface Field { key: string; label: string; type?: string; required?: boolean; options?: string[]; }
interface Config { title: string; icon: string; description: string; path: string; create?: string; fields: Field[]; columns: string[]; remove?: boolean; }

const pages: Record<string, Config> = {
  students: { title: 'Students', icon: 'bi-people', description: 'Manage student records, levels and contact details.', path: '/students', create: '/students', columns: ['userId.name', 'studentCode', 'grade', 'userId.phone', 'isActive', 'createdAt'], fields: [{ key: 'name', label: 'Full name', required: true }, { key: 'phone', label: 'Phone', required: true }, { key: 'password', label: 'Password', type: 'password', required: true }, { key: 'parentPhone', label: 'Parent phone', required: true }, { key: 'gender', label: 'Gender', type: 'select', required: true, options: ['male', 'female'] }, { key: 'grade', label: 'Grade', required: true }, { key: 'teacherId', label: 'Teacher profile ID', required: true }] },
  teachers: { title: 'Teachers', icon: 'bi-person-workspace', description: 'Manage Teachers and their teaching subjects.', path: '/teachers', create: '/teachers', columns: ['userId.name', 'subject', 'userId.phone', 'isActive', 'createdAt'], fields: [{ key: 'name', label: 'Full name', required: true }, { key: 'phone', label: 'Phone', required: true }, { key: 'password', label: 'Password', type: 'password', required: true }, { key: 'subject', label: 'Subject' }, { key: 'description', label: 'Description', type: 'textarea' }] },
  courses: { title: 'Courses', icon: 'bi-journal-bookmark', description: 'Create and organize courses for your center.', path: '/courses', create: '/courses', remove: true, columns: ['name', 'code', 'duration', 'isActive', 'createdAt'], fields: [{ key: 'name', label: 'Course name', required: true }, { key: 'code', label: 'Course code' }, { key: 'duration', label: 'Duration (hours)', type: 'number' }, { key: 'description', label: 'Description', type: 'textarea' }] },
  classes: { title: 'Classes', icon: 'bi-easel2', description: 'Manage groups, capacity and instructor assignments.', path: '/groups', create: '/groups', remove: true, columns: ['groupName', 'gradeLevelId.name', 'teacherId.userId.name', 'maxCapacity', 'sessionPrice', 'isActive'], fields: [{ key: 'groupName', label: 'Class name', required: true }, { key: 'gradeLevelId', label: 'Grade ID', required: true }, { key: 'teacherId', label: 'Teacher profile ID', required: true }, { key: 'maxCapacity', label: 'Capacity', type: 'number' }, { key: 'sessionPrice', label: 'Session price', type: 'number', required: true }] },
  exams: { title: 'Exams', icon: 'bi-clipboard2-check', description: 'Plan, publish and track examinations.', path: '/exams', create: '/exams', remove: true, columns: ['title', 'group.groupName', 'examDate', 'totalMarks', 'status'], fields: [{ key: 'title', label: 'Exam title', required: true }, { key: 'group', label: 'Class ID', required: true }, { key: 'teacher', label: 'Teacher profile ID', required: true }, { key: 'examDate', label: 'Exam date', type: 'date', required: true }, { key: 'totalMarks', label: 'Total marks', type: 'number', required: true }, { key: 'passingMarks', label: 'Passing marks', type: 'number', required: true }, { key: 'duration', label: 'Duration (minutes)', type: 'number', required: true }] },
  attendance: { title: 'Attendance', icon: 'bi-calendar2-check', description: 'Record and review class attendance.', path: '/attendance/allattendance', create: '/attendance/create', remove: true, columns: ['studentId.userId.name', 'groupId.groupName', 'date', 'status', 'method'], fields: [{ key: 'studentId', label: 'Student ID', required: true }, { key: 'groupId', label: 'Class ID', required: true }, { key: 'date', label: 'Date', type: 'date', required: true }, { key: 'status', label: 'Status', type: 'select', required: true, options: ['Present', 'Absent', 'Late', 'Excused'] }, { key: 'method', label: 'Method', type: 'select', options: ['Manual', 'QR', 'NFC', 'Barcode'] }] },
  payments: { title: 'Payments', icon: 'bi-credit-card', description: 'Track fees due, payments received and balances.', path: '/payments', create: '/payments', columns: ['studentId.userId.name', 'groupId.groupName', 'amountDue', 'amountPaid', 'remaining', 'status'], fields: [{ key: 'studentId', label: 'Student ID', required: true }, { key: 'groupId', label: 'Class ID', required: true }, { key: 'sessionDate', label: 'Session date', type: 'date', required: true }, { key: 'amountDue', label: 'Amount due', type: 'number', required: true }, { key: 'amountPaid', label: 'Amount paid', type: 'number' }] },
  messages: { title: 'Messages', icon: 'bi-chat-left-text', description: 'Send announcements to your learning community.', path: '/notifications', create: '/notifications', remove: true, columns: ['title', 'body', 'type', 'targetRole', 'createdAt'], fields: [{ key: 'title', label: 'Title', required: true }, { key: 'body', label: 'Message', type: 'textarea', required: true }, { key: 'type', label: 'Type', type: 'select', options: ['announcement', 'payment', 'exam', 'attendance'] }, { key: 'targetRole', label: 'Audience', type: 'select', options: ['all', 'students', 'parents', 'teachers'] }] }
};

@Component({ selector: 'app-management-page', templateUrl: './management-page.component.html', styleUrls: ['./management-page.component.css'] })
export class ManagementPageComponent implements OnInit, OnDestroy {
  config: Config = pages['students']; rows: Record<string, unknown>[] = []; form: Record<string, unknown> = {}; loading = true; saving = false; deleting = false; open = false; pendingDelete: Record<string, unknown> | null = null; search = ''; error = ''; message = ''; private subscription?: Subscription;
  constructor(private readonly route: ActivatedRoute, private readonly api: ApiService) {}
  ngOnInit(): void { this.subscription = this.route.data.subscribe((data) => { this.config = pages[String(data['resource'])] || pages['students']; this.resetForm(); this.load(); }); }
  ngOnDestroy(): void { this.subscription?.unsubscribe(); }
  load(): void { this.loading = true; this.error = ''; this.api.list(this.config.path).subscribe({ next: (rows) => { this.rows = rows; this.loading = false; }, error: (e: { error?: { message?: string } }) => { this.error = e.error?.message || 'Could not load data. Please check the API server and permissions.'; this.loading = false; } }); }
  get filtered(): Record<string, unknown>[] { const term = this.search.trim().toLowerCase(); return term ? this.rows.filter((row) => this.config.columns.some((key) => this.value(row, key).toLowerCase().includes(term))) : this.rows; }
  save(): void { if (!this.config.create) return; this.saving = true; const data = Object.fromEntries(Object.entries(this.form).filter(([, value]) => value !== '')); this.api.post(this.config.create, data).subscribe({ next: () => { this.saving = false; this.open = false; this.message = 'Record created successfully.'; this.load(); }, error: (e: { error?: { message?: string } }) => { this.saving = false; this.error = e.error?.message || 'Could not save this record.'; } }); }
  requestDelete(row: Record<string, unknown>): void { if (this.config.remove && row['_id']) this.pendingDelete = row; }
  cancelDelete(): void { if (!this.deleting) this.pendingDelete = null; }
  confirmDelete(): void {
    const row = this.pendingDelete;
    if (!this.config.remove || !row || !row['_id']) return;
    this.deleting = true;
    this.api.delete(`${this.config.path.replace('/allattendance', '')}/${String(row['_id'])}`).subscribe({
      next: () => { this.deleting = false; this.pendingDelete = null; this.message = 'Record deleted successfully.'; this.load(); },
      error: (e: { error?: { message?: string } }) => { this.deleting = false; this.error = e.error?.message || 'Could not delete this record.'; }
    });
  }
  value(row: Record<string, unknown>, key: string): string { const value = key.split('.').reduce<unknown>((current, part) => current && typeof current === 'object' ? (current as Record<string, unknown>)[part] : undefined, row); if (value === true) return 'Active'; if (value === false) return 'Inactive'; if (value === undefined || value === null || value === '') return '-'; if (typeof value === 'string' && /date|created/i.test(key) && !Number.isNaN(Date.parse(value))) return new Date(value).toLocaleDateString(); return String(value); }
  label(key: string): string { return key.split('.').pop()?.replace(/([A-Z])/g, ' $1').replace(/^./, (v) => v.toUpperCase()) || key; }
  private resetForm(): void { this.form = Object.fromEntries(this.config.fields.map((field) => [field.key, ''])); }
}
